### ISSUE TITLE
css box shadow artifacts

### ISSUE THREAD

**Issue by newor0599** [linkfrg/ignis#113]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Information

 ```
Ignis 0.4.dev0
Branch: main
Commit: 3aeb1a4d48dff9fa9e678ff68f442b58aed10435 (fix(network): Vpn: notify `active-vpn-id` & `is-connected` when adding/removing an active connection)
Current desktop: Hyprland

os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

### Description

![latest-screenshot](https://github.com/user-attachments/assets/6cb5d539-3a7c-4291-aaf7-189fc928ad8a)

Using box shadow on elements create this line artifact

### How to reproduce

Apply box shadow with css on any element

### Logs, images, videos, config files, CSS/SCSS files
``` css
scale{
  slider{
    opacity: 0;
  }
  trough{
    background:colors.$ui-second;
    border:none;
    border-radius: 100px;
    box-shadow: 0 0 5px 3px colors.$ui-shadow;
    highlight{
      background: colors.$ui-white;
      border:none;
      border-radius:100px;
      min-height: s.$popup-size;
      min-width: 0px;
    }
  }
}
```

**Comment by linkfrg** [comment]
I tried the SCSS code you shared + took out part of your config (volume popup) and don't see any artifacts

Please share the part of the config + SCSS that fully reproduces the issue, then it will be easier for me to help you

**Comment by newor0599** [comment]
```css
scale{
  slider{
    opacity: 0;
  }
  trough{
    background:colors.$ui-second;
    border:none;
    border-radius: 100px;
    box-shadow: 0 0 5px 3px colors.$ui-shadow;
    highlight{
      background: colors.$ui-white;
      border:none;
      border-radius:100px;
      min-height: s.$popup-size;
      min-width: 0px;
    }
  }
}
```
Sorry, I also can't reproduce with the css I provided in the issue :p
This css should reproduce it
